//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorLookupTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorLookupTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Name&quot;,&quot;Hex (24 bit)&quot;,&quot;Red (8 bit)&quot;,&quot;Green (8 bit)&quot;,&quot;Blue (8 bit)&quot;,&quot;Hue (degrees)&quot;,&quot;HSL.S (%)&quot;,&quot;HSL.L (%), HSV.S (%), HSV.V (%)&quot;
        ///&quot;Absolute zero&quot;,&quot;#0048BA&quot;,0,72,186,217.0,100.0,37.0
        ///&quot;Acid green&quot;,&quot;#B0BF1A&quot;,176,191,26,65.0,76.0,43.0
        ///&quot;Aero&quot;,&quot;#7CB9E8&quot;,124,185,232,206.0,70.0,70.0
        ///&quot;Aero blue&quot;,&quot;#C9FFE5&quot;,201,255,229,151.0,100.0,89.0
        ///&quot;African violet&quot;,&quot;#B284BE&quot;,178,132,190,288.0,31.0,63.0
        ///&quot;Air Force blue (RAF)&quot;,&quot;#5D8AA8&quot;,93,138,168,204.0,30.0,51.0
        ///&quot;Air Force blue (USAF)&quot;,&quot;#00308F&quot;,0,48,143,220.0,100.0,28.0
        ///&quot;Ai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string colors {
            get {
                return ResourceManager.GetString("colors", resourceCulture);
            }
        }
    }
}
